#!/usr/bin/env python3

import os
import sys

COMMANDS= [
'awk -f day1-1.awk day1-input1',
'tclsh day1-2.tcl'
]

if len(sys.argv) != 3:
    print("Usage: ./solve <day> <problem number>")
    exit(1)

try:
    day = int(sys.argv[1])
    number = int(sys.argv[2])
    assert 1 <= day <= 25
    assert 1 <= number <= 2
except:
    print("Usage: ./solve <day> <problem number>")
    exit(1)

command = COMMANDS[(day - 1) * 2 + number - 1]
os.system(command)

